### ISSUE TITLE
Question - Do we need to call the free function in OCaml?

### ISSUE THREAD

**Issue by patrick-nicodemus** [zshipko/futhark-bindgen#3]
I am using OCaml to write a wrapper for my Futhark program. OCaml is a garbage collected language, so if I dynamically allocate an array, I don't have to think about deallocating it, the garbage collector does it for me.

Now, say I create a new Futhark context, then allocate an array in OCaml.
```ocaml
let ctx = Context.v
            ~debug:false ~log:false ~profile:false ~auto_sync:true ()
let pt_cloud= read_pt_cloud file (* pt_cloud_array is a 2D Bigarray.Genarray *)
let z = Array_f64_2d.v ctx pt_cloud
let m = my_futhark_fn ctx z
```
I assume this `Array_f64_2d.v` merely "registers" the array `pt_cloud` with the Futhark context and creates some small overhead data structure with pointers to it.
Now I call a Futhark function, get my result.

I am now confused about what to do with the Futhark 2D array `z` I constructed on top of my OCaml array. I was thinking that I should call the Futhark function `Array_f64_2d.free z`  but it's not clear to me how that interacts with OCaml's garbage collection system. When I run the code without calling any free functions, it seems to work, but I'm unclear on whether I'm creating a memory leak by not deallocating the resources. Conversely when I run the code and use the free functions, I hit a bunch of segfaults in my OCaml code and I'm not sure how to get around them. It's occurring to me that these segfaults might be caused by the garbage collector trying to collect memory which has already been deallocated by Futhark.

Do you have any advice on how to proceed here?
Thank you very much!

**Comment by zshipko** [comment]
I don't think it is necessary to call `free`, it should be called automatically when the value gets garbage collected: https://github.com/zshipko/futhark-bindgen/blob/b9ae50a0feecc78dfc349911424cc3066ee63c13/src/generate/templates/ocaml/array.ml#L19

Perhaps it's worth removing it from the public API, but I do think there are cases when working with large arrays where you want to ensure when some large value is cleaned up.

It does seem like the segfaults you mentioned are because `free` is being called twice - I will take a look a fixing that.

**Comment by zshipko** [comment]
Just opened https://github.com/zshipko/futhark-bindgen/pull/4 - let me know if that fixes the segfaults and I can make a new release

**Comment by patrick-nicodemus** [comment]
@zshipko Yes, thank you! It does seem work, my program runs fine. I think that the segfault only occurs when the garbage collector actually runs so I think you have to allocate a decent amount of new memory after freeing to trigger the garbage collector and thus trigger the bug. I am able to produce it (on master) with the following code:
```ocaml
open Bigarray

let ctx = my_futhark_program.Context.v
            ~debug:false ~log:false ~profile:false ~auto_sync:true ()

let () =
  let open my_futhark_program in
  for i = 0 to 1000 do
    let a = Genarray.init Float64 c_layout [| 100; 100 |] (fun _ -> Float.of_int i) in
    let p = Array_f64_2d.v ctx a in
    Array_f64_2d.free p
  done
```

if you want to add something like this to the tests. But yeah, the fix appears to work, I don't get the segfaults anymore.  👍

**Comment by zshipko** [comment]
Thanks! I added your example to the tests and just published a new release.
